### ISSUE TITLE
[feature request] allow reading integration credentials from ENV vars

### ISSUE THREAD

**Issue by swiknaba** [duosecurity/duo_openvpn_as#17]
### Problem
I want to automate launching OpenVPN using Docker. In my Dockerfile, I'm now pulling in the python file, and then I have to manually replace the credentials.
I want to build the Docker image e.g. on a CI/CD pipeline, where I want to have my duo credentials stored. Passing them in now requires me to do some dark magic, like e.g.

```docker
RUN sed -i "s/<DUO[[:space:]]INTEGRATION[[:space:]]KEY[[:space:]]HERE>/"${DUO_INTEGRATION_KEY}"/g" duosecurity/duo_openvpn_as.py && \
    sed -i "s/<DUO[[:space:]]INTEGRATION[[:space:]]SECRET[[:space:]]KEY[[:space:]]HERE>/"${DUO_INTEGRATION_SECRET}"" duosecurity/duo_openvpn_as.py && \
    sed -i "s/<DUO[[:space:]]API[[:space:]]HOSTNAME[[:space:]]HERE>/"${DUO_API_HOSTNAME}"" duosecurity/duo_openvpn_as.py
```

to replace the credentials. This is brittle and not really nice. Also if you change the strings, my setup will break. Also, `sed` has encoding and escaping issues.

### Solution
Allow `duo_openvpn_as.py` to read the credentials from environment variables. I.e. instead of 

```python
IKEY = '<DUO INTEGRATION KEY HERE>'
```

we would have sth. like
```python
IKEY = os.environ.get('DUO_INTEGRATION_KEY')
```

by default.

**Comment by AaronAtDuo** [comment]
Closing out old tickets
