### ISSUE TITLE
Openvpn Access server v2.0.25

### ISSUE THREAD

**Issue by gtb999** [duosecurity/duo_openvpn_as#3]
Hello
I have been using this script for several years but i updated from AS 2.0.17 to 2.0.25 today and it stopped working. The internet access from our openvpn server is via a squid v3.3. proxy. The connection to the duo server fails with an InvalidCertificateException "returned an invalid certificate (hostname mismatch)". I wonder if it is to do with a change in the bundled python version. It looks like it is validating the proxy hostname against the duosecurity certificate
Thanks

**Comment by mschwager** [comment]
Possibly related to https://github.com/duosecurity/duo_openvpn_as/commit/8b599890ede76b14257488283eacb911a30f5d2e?

Thanks for bringing this to our attention!

**Comment by BradleyHiggins** [comment]
Hi gtb999, I've reproduced this issue, fix coming shortly.

Thanks for using Duo!

**Comment by BradleyHiggins** [comment]
Should be all set!  Fixed in ff8c9cc.

**Comment by gtb999** [comment]
Thanks for the prompt attention Bradley!

I updated the script with v2.2 but i still get the same issue. The full exception is below. I made a mistake with the squid version - its 3.1.23, which is the latest version available in the Amazon Linux repository (proxy server is running in AWS)

Many thanks

Mar 18 08:36:16 localhost openvpnas: Duo OpenVPN_AS: Traceback (most recent call last):#012  File "<string>", line 664, in post_auth_cr#012  File "<string>", line 557, in preauth#012  File "<string>", line 375, in json_api_call#012  File "<string>", line 546, in api_call#012  File "<string>", line 362, in api_call#012  File "/usr/local/openvpn_as/lib/python2.7/httplib.py", line 1053, in request#012    self._send_request(method, url, body, headers)#012  File "/usr/local/openvpn_as/lib/python2.7/httplib.py", line 1093, in _send_request#012    self.endheaders(body)#012  File "/usr/local/openvpn_as/lib/python2.7/httplib.py", line 1049, in endheaders#012    self._send_output(message_body)#012  File "/usr/local/openvpn_as/lib/python2.7/httplib.py", line 893, in _send_output#012    self.send(msg)#012  File "/usr/local/openvpn_as/lib/python2.7/httplib.py", line 855, in send#012    self.connect()#012  File "<string>", line 524, in connect#012InvalidCertificateException: Host squid-proxy.mydomain.com returned an invalid certificate (hostname mismatch): {'crlDistributionPoints': (u'http://crl3.digicert.com/sha2-ha-server-g1.crl', u'http://crl4.digicert.com/sha2-ha-server-g1.crl'), 'subjectAltName': (('DNS', '*.duosecurity.com'), ('DNS', 'duosecurity.com')), 'notBefore': u'Oct 22 12:00:01 2013 GMT', 'caIssuers': (u'http://cacerts.digicert.com/DigiCertSHA2HighAssuranceServerCA.crt',), 'OCSP': (u'http://ocsp.digicert.com',), 'serialNumber': u'03CBE781655532FAE641E04B268E6A52', 'notAfter': 'Jan  4 12:00:00 2017 GMT', 'version': 3L, 'subject': ((('countryName', u'US'),), (('stateOrProvinceName', u'Michigan'),), (('localityName', u'Ann Arbor'),), (('organizationName', u'Duo Security, Inc.'),), (('commonName', u'*.duosecurity.com'),)), 'issuer': ((('countryName', u'US'),), (('organizationName', u'DigiCert Inc'),), (('organizationalUnitName', u'www.digicert.com'),), (('commonName', u'DigiCert SHA2 High Assurance Server CA'),))}#012To learn more, see http://code.google.com/appengine/kb/general.html#rpcssl

**Comment by BradleyHiggins** [comment]
> I updated the script with v2.2
https://duo.com/docs/openvpn_as#enable-the-post-auth-script
Make sure you run the steps listed in the docs here.  OpenVPN does not run the python code from /usr/local/openvpn_as/scripts/, it actually copies the script into a sqlite db and runs it from there.  Have you run the sacli ConfigPut and Reset commands?  If you haven't run those commands since updating the duo_openvpn_as.py file to v2.2, you're still running the old code.

**Comment by gtb999** [comment]
ahhh, my apologies. You are completely correct. I had copied the file into the right place but I had not run those commands. It works now! thank you very much.
